# Generated by Django 5.1.1 on 2024-09-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discretion', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=50)),
                ('designationDiscretion', models.CharField(max_length=500)),
                ('birthDay', models.DateField()),
                ('websiteLink', models.URLField(max_length=1000)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('degree', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('clients', models.IntegerField()),
                ('project', models.IntegerField()),
                ('supportHours', models.IntegerField()),
                ('workers', models.IntegerField()),
            ],
        ),
    ]
